export const OpenaiArtworkExampleResponse = {
    "status": "PROCESSED",
    "comicData": [
        {
            "panels": [
                {
                    "panel": 0,
                    "instruction": "An Indian girl with (black long hair), 12 years old, with black long hair, wearing a (white T-shirt), blue jeans, white sneakers, in front of the Eiffel tower in Paris, carrying a small backpack",
                    "caption": "An Indian girl with (black long hair), 12 years old, with black long hair, wearing a (white T-shirt), blue jeans, white sneakers, in front of the Eiffel tower in Paris, carrying a small backpack",
                    "image": "https://s.llamagen.ai/a76b63ea-9e3d-41c4-b1a2-727509ed38e1.webp",
                    "bgImage": "https://s.llamagen.ai/running_girl_1.png",
                    "location": "",
                    "time": "",
                    "lighting": "",
                    "cameraShot": "",
                    "cameraMovement": "",
                    "characters": [],
                    "seed": null,
                    "prompt": "An Indian girl with (black long hair), 12 years old, with black long hair, wearing a (white T-shirt), blue jeans, white sneakers, in front of the Eiffel tower in Paris, carrying a small backpack",
                    "negativePrompt": "",
                    "runId": "cm1599ue4000bkz031sim37t0:0",
                    "assetUrl": "https://s.llamagen.ai/cm1599ue4000bkz031sim37t0-0.webp"
                },
                {
                    "panel": 1,
                    "instruction": "a Pixar animation,3D style An Indian An Indian girl with (black long hair), 12 years old, with black long hair, ((Comfortable white cotton t-shirt, blue jeans, and white sneakers with colorful laces.)) Standing in a vibrant, spacious broadcast hall with yellow, pink, and blue walls. Overhead stage lighting rig with multicolored spotlights. Hundreds of colorful musical notes floating in the air. Large speaker in a corner emitting musical notes. Reflective wooden floor with colorful light reflections. Boy looking around with a determined expression, scanning the room. Dynamic pose, one arm raised. Energetic and musical atmosphere. Highly detailed, cinematic lighting with strong color contrasts.",
                    "caption": "a Pixar animation,3D style An Indian An Indian girl with (black long hair), 12 years old, with black long hair, ((Comfortable white cotton t-shirt, blue jeans, and white sneakers with colorful laces.)) Standing in a vibrant, spacious broadcast hall with yellow, pink, and blue walls. Overhead stage lighting rig with multicolored spotlights. Hundreds of colorful musical notes floating in the air. Large speaker in a corner emitting musical notes. Reflective wooden floor with colorful light reflections. Boy looking around with a determined expression, scanning the room. Dynamic pose, one arm raised. Energetic and musical atmosphere. Highly detailed, cinematic lighting with strong color contrasts.",
                    "image": "https://s.llamagen.ai/a76b63ea-9e3d-41c4-b1a2-727509ed38e1.webp",
                    "bgImage": "https://s.llamagen.ai/running_girl_2.png",
                    "location": "",
                    "time": "",
                    "lighting": "",
                    "cameraShot": "",
                    "cameraMovement": "",
                    "characters": [],
                    "seed": null,
                    "prompt": "a Pixar animation,3D style An Indian An Indian girl with (black long hair), 12 years old, with black long hair, ((Comfortable white cotton t-shirt, blue jeans, and white sneakers with colorful laces.)) Standing in a vibrant, spacious broadcast hall with yellow, pink, and blue walls. Overhead stage lighting rig with multicolored spotlights. Hundreds of colorful musical notes floating in the air. Large speaker in a corner emitting musical notes. Reflective wooden floor with colorful light reflections. Boy looking around with a determined expression, scanning the room. Dynamic pose, one arm raised. Energetic and musical atmosphere. Highly detailed, cinematic lighting with strong color contrasts.",
                    "negativePrompt": "",
                    "runId": "cm1599ue4000bkz031sim37t0:1",
                    "assetUrl": "https://s.llamagen.ai/cm1599ue4000bkz031sim37t0-1.webp"
                },
                {
                    "panel": 2,
                    "instruction": "a Pixar animation,3D style An Indian An Indian girl with (black long hair), 12 years old, with black long hair, ((Comfortable white cotton t-shirt, blue jeans, and white sneakers with colorful laces.)) Standing with his feet slightly apart, hands clasped together in front of his chest as if concentrating his power. Eyes gently closed, eyebrows slightly furrowed in deep concentration. A serene smile playing on his lips. (((Intense, brilliant pure white energy radiating from the boy's entire body))), creating a dazzling aura like a soft starburst. The white energy flows outward in smooth, wavy patterns, brightest around his clasped hands. Shimmering particles of light swirling around the boy, emphasizing the energy flow. Background of broadcast hall visible but softened by the radiant glow. Boy's overall expression conveying peaceful concentration as he channels his new ability. Highly detailed, magical and inspiring mood. Friendly, dynamic composition focusing on the boy's amazing transformation, perfect for young viewers.",
                    "caption": "a Pixar animation,3D style An Indian An Indian girl with (black long hair), 12 years old, with black long hair, ((Comfortable white cotton t-shirt, blue jeans, and white sneakers with colorful laces.)) Standing with his feet slightly apart, hands clasped together in front of his chest as if concentrating his power. Eyes gently closed, eyebrows slightly furrowed in deep concentration. A serene smile playing on his lips. (((Intense, brilliant pure white energy radiating from the boy's entire body))), creating a dazzling aura like a soft starburst. The white energy flows outward in smooth, wavy patterns, brightest around his clasped hands. Shimmering particles of light swirling around the boy, emphasizing the energy flow. Background of broadcast hall visible but softened by the radiant glow. Boy's overall expression conveying peaceful concentration as he channels his new ability. Highly detailed, magical and inspiring mood. Friendly, dynamic composition focusing on the boy's amazing transformation, perfect for young viewers.",
                    "image": "https://s.llamagen.ai/a76b63ea-9e3d-41c4-b1a2-727509ed38e1.webp",
                    "bgImage": "https://s.llamagen.ai/running_girl_3.png",
                    "location": "",
                    "time": "",
                    "lighting": "",
                    "cameraShot": "",
                    "cameraMovement": "",
                    "characters": [],
                    "seed": null,
                    "prompt": "a Pixar animation,3D style An Indian An Indian girl with (black long hair), 12 years old, with black long hair, ((Comfortable white cotton t-shirt, blue jeans, and white sneakers with colorful laces.)) Standing with his feet slightly apart, hands clasped together in front of his chest as if concentrating his power. Eyes gently closed, eyebrows slightly furrowed in deep concentration. A serene smile playing on his lips. (((Intense, brilliant pure white energy radiating from the boy's entire body))), creating a dazzling aura like a soft starburst. The white energy flows outward in smooth, wavy patterns, brightest around his clasped hands. Shimmering particles of light swirling around the boy, emphasizing the energy flow. Background of broadcast hall visible but softened by the radiant glow. Boy's overall expression conveying peaceful concentration as he channels his new ability. Highly detailed, magical and inspiring mood. Friendly, dynamic composition focusing on the boy's amazing transformation, perfect for young viewers.",
                    "negativePrompt": "",
                    "runId": "cm1599ue4000bkz031sim37t0:2",
                    "assetUrl": "https://s.llamagen.ai/cm1599ue4000bkz031sim37t0-2.webp"
                },
                {
                    "panel": 3,
                    "instruction": "a Pixar animation,3D style An Indian An Indian girl with (black long hair), 12 years old, with black long hair ((Comfortable white cotton t-shirt, blue jeans, and white sneakers with colorful laces.)) Running joyfully on the colorful stage of the broadcast hall. White streaks beginning to form behind the boy, indicating speed. Vibrant background with multicolored stage lights. More musical notes surrounding the boy, floating in various colors. Confetti-like particles in the air. Reflective wooden floor. Energetic and lively atmosphere. Boy's expression showing excitement and determination. Highly detailed, dynamic running pose with arms pumping. Cinematic lighting emphasizing the start of super-speed.",
                    "caption": "a Pixar animation,3D style An Indian An Indian girl with (black long hair), 12 years old, with black long hair ((Comfortable white cotton t-shirt, blue jeans, and white sneakers with colorful laces.)) Running joyfully on the colorful stage of the broadcast hall. White streaks beginning to form behind the boy, indicating speed. Vibrant background with multicolored stage lights. More musical notes surrounding the boy, floating in various colors. Confetti-like particles in the air. Reflective wooden floor. Energetic and lively atmosphere. Boy's expression showing excitement and determination. Highly detailed, dynamic running pose with arms pumping. Cinematic lighting emphasizing the start of super-speed.",
                    "image": "https://s.llamagen.ai/a76b63ea-9e3d-41c4-b1a2-727509ed38e1.webp",
                    "bgImage": "https://s.llamagen.ai/running_girl_4.png",
                    "location": "",
                    "time": "",
                    "lighting": "",
                    "cameraShot": "",
                    "cameraMovement": "",
                    "characters": [],
                    "seed": null,
                    "prompt": "a Pixar animation,3D style An Indian An Indian girl with (black long hair), 12 years old, with black long hair ((Comfortable white cotton t-shirt, blue jeans, and white sneakers with colorful laces.)) Running joyfully on the colorful stage of the broadcast hall. White streaks beginning to form behind the boy, indicating speed. Vibrant background with multicolored stage lights. More musical notes surrounding the boy, floating in various colors. Confetti-like particles in the air. Reflective wooden floor. Energetic and lively atmosphere. Boy's expression showing excitement and determination. Highly detailed, dynamic running pose with arms pumping. Cinematic lighting emphasizing the start of super-speed.",
                    "negativePrompt": "",
                    "runId": "cm1599ue4000bkz031sim37t0:3",
                    "assetUrl": "https://s.llamagen.ai/cm1599ue4000bkz031sim37t0-3.webp"
                },
                {
                    "panel": 4,
                    "instruction": "a Pixar animation,3D style An Indian An Indian girl with (black long hair), 12 years old, with black long hair ((Comfortable white cotton t-shirt, blue jeans, and white sneakers with colorful laces.)) Running at full super-speed from left to right in the broadcast hall. Prominent white light trails behind the boy, emphasizing super speed. Background blurred due to speed, with only white and yellow visible. Large, bright yellow musical notes floating in the air. Boy's hand reaching out to grab a musical note. Joyful, focused expression on the boy's face. Dynamic pose with hair and clothes in motion. Magical atmosphere with particles and light effects. Strong contrast between the golden notes and the blurred background. Cinematic composition capturing the climax of the chase.",
                    "caption": "a Pixar animation,3D style An Indian An Indian girl with (black long hair), 12 years old, with black long hair ((Comfortable white cotton t-shirt, blue jeans, and white sneakers with colorful laces.)) Running at full super-speed from left to right in the broadcast hall. Prominent white light trails behind the boy, emphasizing super speed. Background blurred due to speed, with only white and yellow visible. Large, bright yellow musical notes floating in the air. Boy's hand reaching out to grab a musical note. Joyful, focused expression on the boy's face. Dynamic pose with hair and clothes in motion. Magical atmosphere with particles and light effects. Strong contrast between the golden notes and the blurred background. Cinematic composition capturing the climax of the chase.",
                    "image": "https://s.llamagen.ai/a76b63ea-9e3d-41c4-b1a2-727509ed38e1.webp",
                    "bgImage": "https://s.llamagen.ai/running_girl_5.png",
                    "location": "",
                    "time": "",
                    "lighting": "",
                    "cameraShot": "",
                    "cameraMovement": "",
                    "characters": [],
                    "seed": null,
                    "prompt": "a Pixar animation,3D style An Indian An Indian girl with (black long hair), 12 years old, with black long hair ((Comfortable white cotton t-shirt, blue jeans, and white sneakers with colorful laces.)) Running at full super-speed from left to right in the broadcast hall. Prominent white light trails behind the boy, emphasizing super speed. Background blurred due to speed, with only white and yellow visible. Large, bright yellow musical notes floating in the air. Boy's hand reaching out to grab a musical note. Joyful, focused expression on the boy's face. Dynamic pose with hair and clothes in motion. Magical atmosphere with particles and light effects. Strong contrast between the golden notes and the blurred background. Cinematic composition capturing the climax of the chase.",
                    "negativePrompt": "",
                    "runId": "cm1599ue4000bkz031sim37t0:4",
                    "assetUrl": "https://s.llamagen.ai/cm1599ue4000bkz031sim37t0-4.webp"
                },
                {
                    "panel": 5,
                    "instruction": "An Indian girl with (black long hair), 12 years old, with black long hair wearing a (white T-shirt), blue jeans, white sneakers, is standing near the Eiffel tower in Paris with great satisfaction. There are white streak lines trailing behind him as if he moved at super speed. She is holding a plain, round, brown cookie.",
                    "caption": "An Indian girl with (black long hair), 12 years old, with black long hair wearing a (white T-shirt), blue jeans, white sneakers, is standing near the Eiffel tower in Paris with great satisfaction. There are white streak lines trailing behind him as if he moved at super speed. She is holding a plain, round, brown cookie.",
                    "image": "https://s.llamagen.ai/a76b63ea-9e3d-41c4-b1a2-727509ed38e1.webp",
                    "bgImage": "https://cdn.llamagen.ai/bg/07171520_panel_6.png",
                    "location": "",
                    "time": "",
                    "lighting": "",
                    "cameraShot": "",
                    "cameraMovement": "",
                    "characters": [],
                    "seed": null,
                    "prompt": "An Indian girl with (black long hair), 12 years old, with black long hair wearing a (white T-shirt), blue jeans, white sneakers, is standing near the Eiffel tower in Paris with great satisfaction. There are white streak lines trailing behind him as if he moved at super speed. She is holding a plain, round, brown cookie.",
                    "negativePrompt": "",
                    "runId": "cm1599ue4000bkz031sim37t0:5",
                    "assetUrl": "https://s.llamagen.ai/cm1599ue4000bkz031sim37t0-5.webp"
                }
            ],
            "gender": "female",
            "age": 25
        }
    ]
};