import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import Image from "next/image";
import Link from "next/link";
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-black`}
      >
        <div className="container flex items-center justify-between  md:py-6 py-3 px-1 md:px-10">
          <div className="flex">
            <Link
              href="/"
              className="flex no-underline cursor-pointer space-x-2 max-sm:mr-0 items-center"
            >
              <Image
                alt="logo"
                width={32}
                height={32}
                className="object-contain"
                src={"/icons/light-logo-v3.jpg"}
              />
              <div className="flex md:flex-row md:items-center  relative   ">
                <Image
                  alt="logo"
                  width={256}
                  height={31}
                  className="md:w-32 w-28 object-contain"
                  src={"/icons/LlamaGen.Ai-word-white.png"}
                />
              </div>
            </Link>
          </div>
        </div>

        {children}
      </body>
    </html>
  );
}
